#!/usr/bin/env python3
import json, os, struct, subprocess, sys, tempfile, uuid, zlib
from pathlib import Path
R=Path(sys.argv[1])
def p(cmd,*args,data="",binary=False):
    kw={"capture_output":True}
    if binary:kw["input"]=data
    else:kw.update(input=data,text=True)
    r=subprocess.run([sys.executable,str(R),cmd,*map(str,args)],**kw)
    if r.returncode:raise AssertionError(f"{cmd}: {r.stderr!r}")
    return r
def j(cmd,*args,data=""):return json.loads(p(cmd,*args,data=data).stdout)
def ok(n,c,q):
    if not c:raise AssertionError(n)
    q.append(n)
def pad4(b):return b+b"\0"*((-len(b))%4)
def make_dtb():
    strings=b"compatible\0description\0"; comp=0;desc=len(b"compatible\0")
    s=b""
    s+=struct.pack(">I",1)+pad4(b"\0")
    s+=struct.pack(">III",3,5,comp)+pad4(b"test\0")
    s+=struct.pack(">I",1)+pad4(b"images\0")
    s+=struct.pack(">I",1)+pad4(b"kernel\0")
    s+=struct.pack(">III",3,7,desc)+pad4(b"kernel\0")
    s+=struct.pack(">I",2)+struct.pack(">I",2)
    s+=struct.pack(">I",1)+pad4(b"configurations\0")
    s+=struct.pack(">I",1)+pad4(b"conf-1\0")
    s+=struct.pack(">III",3,7,desc)+pad4(b"config\0")
    s+=struct.pack(">I",2)+struct.pack(">I",2)
    s+=struct.pack(">I",2)+struct.pack(">I",9)
    off_r=40;off_s=56;off_str=off_s+len(s);total=off_str+len(strings)
    h=struct.pack(">10I",0xd00dfeed,total,off_s,off_str,off_r,17,16,0,len(strings),len(s))
    return h+b"\0"*16+s+strings
def acpi(sig,length):
    d=bytearray(length);d[:4]=sig.encode();struct.pack_into("<I",d,4,length);d[8]=2;d[10:16]=b"OEMID ";d[16:24]=b"TABLEID ";d[28:32]=b"PYTH";d[9]=(-sum(d))&0xff;return bytes(d)
def main():
    q=[]
    with tempfile.TemporaryDirectory() as td:
        td=Path(td);dtb=td/"x.dtb";dtb.write_bytes(make_dtb())
        ok("device-tree-fdt-dump",j("device-tree-fdt-dump",dtb)["header"]["version"]==17,q)
        ok("fdt-property-inspector",j("fdt-property-inspector",dtb,"/","compatible")["value"]=="test",q)
        ok("fdt-node-path-search","/images/kernel" in j("fdt-node-path-search",dtb,"kernel"),q)
        payload=b"abc";dcrc=zlib.crc32(payload)&0xffffffff
        hdr=bytearray(64);struct.pack_into(">7I",hdr,0,0x27051956,0,1,len(payload),0x8000,0x8000,dcrc);hdr[28:32]=bytes([5,2,2,0]);hdr[32:36]=b"test";hcrc=zlib.crc32(hdr)&0xffffffff;struct.pack_into(">I",hdr,4,hcrc)
        img=td/"uboot.img";img.write_bytes(hdr+payload);u=j("u-boot-image-header",img);ok("u-boot-image-header",u["header_crc_valid"] and u["data_crc_valid"],q)
        envp=b"a=1\0b=2\0\0";env=td/"env.bin";env.write_bytes((zlib.crc32(envp)&0xffffffff).to_bytes(4,"little")+envp)
        ok("u-boot-env-crc-calc",j("u-boot-env-crc-calc",env)["valid"],q)
        ok("u-boot-fit-image-view",len(j("u-boot-fit-image-view",dtb)["images"])>=1,q)
        cb=td/"cbfs.bin";head=b"LARCHIVE"+struct.pack(">4I",4,1,0,32)+b"x\0"+b"\0"*6;cb.write_bytes(head+b"DATA")
        ok("coreboot-cbfs-parser",j("coreboot-cbfs-parser",cb)["count"]==1,q)
        cap=td/"cap.bin";g=uuid.uuid4();cap.write_bytes(g.bytes_le+struct.pack("<III",28,0,28))
        ok("edkid-uefi-capsule-chk",j("edkid-uefi-capsule-chk",cap)["valid"],q)
        ef=td/f"Var-{uuid.uuid4()}.bin";ef.write_bytes((7).to_bytes(4,"little")+b"abc")
        ok("uefi-variable-dump",j("uefi-variable-dump",ef)["attributes"]=="0x7",q)
        dmi=td/"dmi.bin";dmi.write_bytes(bytes([1,4,1,0,0,0,127,4,0xff,0xff,0,0]))
        ok("smbios-dmi-table-view",j("smbios-dmi-table-view",dmi)["count"]>=1,q)
        ds=td/"dsdt";ds.write_bytes(acpi("DSDT",36));ok("acpi-table-parser-dsdt",j("acpi-table-parser-dsdt",ds)["is_dsdt"],q)
        fa=td/"fadt";fa.write_bytes(acpi("FACP",116));ok("acpi-fadt-header-dump",j("acpi-fadt-header-dump",fa)["is_fadt"],q)
        spdx=td/"s.json";spdx.write_text(json.dumps({"spdxVersion":"SPDX-2.3","SPDXID":"SPDXRef-DOCUMENT","name":"fw","packages":[{"name":"p","SPDXID":"SPDXRef-P"}]}))
        ok("spdx-sbom-firmware-chk",j("spdx-sbom-firmware-chk",spdx)["valid"],q)
        fw=td/"fw.bin";fw.write_bytes(bytes(range(256))*4)
        ok("binwalk-entropy-plot","#" in p("binwalk-entropy-plot",fw,"256").stdout,q)
        crc=f"{zlib.crc32(fw.read_bytes())&0xffffffff:08x}";ok("firmware-crc32-verifier",j("firmware-crc32-verifier",fw,crc)["valid"],q)
        ih=td/"x.hex";ih.write_text(":0400000001020304F2\n:00000001FF\n")
        ok("intel-hex-ihex-converter",j("intel-hex-ihex-converter","parse",ih)[0]["checksum_valid"],q)
        sr=td/"x.srec";sr.write_text("S10500000102F7\n");ok("motorola-srec-parser",j("motorola-srec-parser",sr)[0]["checksum_valid"],q)
        ok("raw-nand-ecc-calculator","parity_hex" in j("raw-nand-ecc-calculator",fw),q)
        ok("nor-flash-sector-align",j("nor-flash-sector-align","0x1001","0x100","0x1000")["erase_start"]=="0x1000",q)
        ok("spi-flash-jedec-id-chk",j("spi-flash-jedec-id-chk","EF4018")["manufacturer"]=="Winbond",q)
        ok("i2c-bus-address-probe",j("i2c-bus-address-probe","0x50")[0]["reserved"] is False,q)
        ok("i2c-smbus-block-calc",len(j("i2c-smbus-block-calc","A00102")["pec_crc8"])==2,q)
        ok("gpio-sysfs-pin-export",j("gpio-sysfs-pin-export","5")["gpio"]==5,q)
        ev=td/"gpio.ev";ev.write_bytes(struct.pack("<QIIII",123,1,7,2,2)+b"\0"*24)
        ok("gpio-cdev-line-event",j("gpio-cdev-line-event",ev)[0]["edge"]=="rising",q)
        ok("uart-baud-rate-divisor","actual_baud" in j("uart-baud-rate-divisor","1843200","115200"),q)
        import termios
        ok("serial-termios-config",j("serial-termios-config",hex(termios.CREAD|termios.CS8))["data_bits"]==8,q)
        usb=td/"usb.bin";usb.write_bytes(bytes.fromhex("120100020000004000000000000000000001"))
        ok("usb-descriptor-parser",j("usb-descriptor-parser",usb)[0]["type_name"]=="Device",q)
        us=td/"str.bin";us.write_bytes(bytes.fromhex("04034100"));ok("usb-string-descriptor",j("usb-string-descriptor",us)["string"]=="A",q)
        ep=td/"ep.bin";ep.write_bytes(bytes.fromhex("07058102000201"));ok("usb-endpoint-analyzer",j("usb-endpoint-analyzer",ep)["direction"]=="IN",q)
        hid=td/"hid.bin";hid.write_bytes(bytes.fromhex("05010906A101C0"));ok("hid-report-descriptor",len(j("hid-report-descriptor",hid))>=3,q)
        ok("can-bus-frame-dumper",j("can-bus-frame-dumper","can0","123#1122")["dlc"]==2,q)
        ok("can-j1939-pgn-parser","pgn" in j("can-j1939-pgn-parser","0x18FEEE00"),q)
        ok("modbus-rtu-crc16-calc","crc16" in j("modbus-rtu-crc16-calc","010300000001"),q)
        ok("modbus-tcp-header-chk",j("modbus-tcp-header-chk","000100000006010300000001")["valid_protocol_id"],q)
        ok("zigbee-zcl-frame-view",j("zigbee-zcl-frame-view","01010A")["command_id"]==10,q)
        ok("ble-gatt-uuid-lookup",j("ble-gatt-uuid-lookup","180F")["assigned_name"]=="Battery Service",q)
        ok("bluetooth-hci-cmd-dump",j("bluetooth-hci-cmd-dump","01030C00")["ocf"]==3,q)
        ok("rfid-mifare-block-chk",j("rfid-mifare-block-chk","FFFFFFFFFFFFFF078069FFFFFFFFFFFF")["valid_complements"],q)
        nd=td/"ndef.bin";nd.write_bytes(bytes.fromhex("D101015458"));ok("nfc-ndef-record-parser",j("nfc-ndef-record-parser",nd)[0]["type"]=="T",q)
        ok("i2s-audio-clock-calc",j("i2s-audio-clock-calc","48000","16","2")["bclk_hz"]==1536000,q)
        ok("pwm-frequency-duty-calc",j("pwm-frequency-duty-calc","1000000","250000")["duty_percent"]==25,q)
        ok("thermal-zone-temp-view",isinstance(j("thermal-zone-temp-view"),list),q)
        ok("cpufreq-scaling-gov",isinstance(j("cpufreq-scaling-gov"),list),q)
        ok("power-supply-status-chk",isinstance(j("power-supply-status-chk"),list),q)
        ok("regulator-voltage-view",isinstance(j("regulator-voltage-view"),list),q)
        nv=td/"nvme.bin";b=bytearray(192);b[1:3]=(300).to_bytes(2,"little");nv.write_bytes(b)
        ok("nvme-smart-log-parser",round(j("nvme-smart-log-parser",nv)["temperature_celsius"],2)==26.85,q)
        vpd=td/"vpd.bin";vpd.write_bytes(bytes.fromhex("00800003414243"));ok("scsi-inquiry-vpd-dump",j("scsi-inquiry-vpd-dump",vpd)["unit_serial_number"]=="ABC",q)
        pc=td/"pci.bin";b=bytearray(64);struct.pack_into("<HH",b,0,0x1234,0x5678);pc.write_bytes(b)
        ok("pci-config-space-dump",j("pci-config-space-dump",pc)["vendor_id"]=="0x1234",q)
        pd=td/"0000:00:00.0";pd.mkdir();(pd/"current_link_speed").write_text("8.0 GT/s");(pd/"current_link_width").write_text("16")
        ok("pci-express-link-speed",j("pci-express-link-speed",pd)["current_link_width"]=="16",q)
        ed=bytearray(128);ed[:8]=b"\x00\xff\xff\xff\xff\xff\xff\x00";m=(1<<10)|(2<<5)|3;ed[8:10]=m.to_bytes(2,"big");ed[10:12]=(1).to_bytes(2,"little");ed[16]=1;ed[17]=36;ed[18]=1;ed[19]=4;ed[126]=0;ed[127]=(-sum(ed))&0xff;ef=td/"edid";ef.write_bytes(ed)
        e=j("edid-monitor-data-parse",ef);ok("edid-monitor-data-parse",e["checksum_valid"] and e["manufacturer"]=="ABC",q)
    if len(q)!=50 or len(set(q))!=50:raise AssertionError(f"expected 50 tests got {len(q)}/{len(set(q))}")
    print("PASS: 50/50 shard-24 functional commands")
if __name__=="__main__":main()
