#!/usr/bin/env python3
import json, os, struct, subprocess, sys, tempfile
from pathlib import Path
R=Path(sys.argv[1])
def p(cmd,*args,data="",binary=False):
    kw={"capture_output":True}
    if binary: kw["input"]=data
    else: kw.update(input=data,text=True)
    r=subprocess.run([sys.executable,str(R),cmd,*map(str,args)],**kw)
    if r.returncode: raise AssertionError(f"{cmd}: {r.stderr!r}")
    return r
def j(cmd,*args,data=""): return json.loads(p(cmd,*args,data=data).stdout)
def ok(n,c,q):
    if not c: raise AssertionError(n)
    q.append(n)
def main():
    q=[]
    with tempfile.TemporaryDirectory() as td:
        f=Path(td)/"perf.bin"; f.write_bytes(struct.pack("<IHH",9,1,8))
        ok("perf-event-sample-view",j("perf-event-sample-view",f)["records"][0]["type"]==9,q)
    ok("hardware-counter-query","devices" in j("hardware-counter-query"),q)
    ok("flamegraph-svg-builder","<svg" in p("flamegraph-svg-builder",data="main;work 3\nmain;idle 1\n").stdout,q)
    perf="sample\n    000 f\n    000 g\n\n"; ok("stackcollapse-perf-cli",";" in p("stackcollapse-perf-cli",data=perf).stdout,q)
    gdb="#0 f ()\n#1 g ()\n\n"; ok("stackcollapse-gdb-tool","g;f" in p("stackcollapse-gdb-tool",data=gdb).stdout,q)
    ok("pmu-cycle-ratio-calc",j("pmu-cycle-ratio-calc","200","100")["cycles_per_instruction"]==2,q)
    ok("branch-mispredict-calc",j("branch-mispredict-calc","5","100")["mispredict_percent"]==5,q)
    ok("cache-miss-rate-analyzer",j("cache-miss-rate-analyzer","10","100")["miss_percent"]==10,q)
    ok("instruction-per-cycle",j("instruction-per-cycle","200","100")["ipc"]==2,q)
    ok("memory-bandwidth-calc",j("memory-bandwidth-calc","1024","2")["bytes_per_second"]==512,q)
    ok("latency-histogram-ascii","|" in p("latency-histogram-ascii","4",data="1 2 3 4").stdout,q)
    ok("percentile-p90-p99-p999",j("percentile-p90-p99-p999",data="1 2 3 4 5")["p99"]>4,q)
    ok("throughput-rps-calc",j("throughput-rps-calc","100","2")["operations_per_second"]==50,q)
    ok("jitter-interarrival-chk","jitter_stddev" in j("jitter-interarrival-chk",data="0 10 21 30"),q)
    ok("hdr-histogram-log-view","summary" in j("hdr-histogram-log-view",data="1,10\n1,20\n"),q)
    ok("malloc-count-hook-cli",j("malloc-count-hook-cli",data="malloc size=64\ncalloc size=32\n")["allocations"]==2,q)
    ok("mmap-allocation-tracer",j("mmap-allocation-tracer",str(os.getpid()))["pid"]==os.getpid(),q)
    ok("brk-heap-expansion-chk",len(j("brk-heap-expansion-chk",str(os.getpid()))["samples"])==1,q)
    ok("page-fault-counter-cli","minor_faults" in j("page-fault-counter-cli",str(os.getpid())),q)
    ok("tlb-miss-ratio-analyzer",j("tlb-miss-ratio-analyzer","2","100")["miss_percent"]==2,q)
    ok("context-switch-cost-est",j("context-switch-cost-est","20")["round_trips"]==20,q)
    ok("thread-pool-saturation",j("thread-pool-saturation","4","4","3")["saturated"] is True,q)
    ok("epoll-latency-bench","supported" in j("epoll-latency-bench","2"),q)
    ok("select-poll-scale-bench",j("select-poll-scale-bench","4")["descriptors"]==4,q)
    ok("io-uring-probe-support","kernel" in j("io-uring-probe-support"),q)
    ok("io-uring-sq-poll-view","threads" in j("io-uring-sq-poll-view"),q)
    ok("futex-contention-timer",j("futex-contention-timer","2","20")["operations"]==40,q)
    ok("spinlock-cycles-wasted",j("spinlock-cycles-wasted","1000")["iterations"]==1000,q)
    bounce=j("cpu-cache-line-bouncing",data="t1 0x1000\nt2 0x1010\n"); ok("cpu-cache-line-bouncing",bounce["suspected_false_sharing_lines"]==1,q)
    ok("numa-memory-distance","nodes" in j("numa-memory-distance"),q)
    ok("sched-wakeup-latency",j("sched-wakeup-latency",data="100 120 200 240")["nanoseconds"]["count"]==2,q)
    ok("irq-cpu-affinity-view",isinstance(j("irq-cpu-affinity-view"),list),q)
    with tempfile.TemporaryDirectory() as td:
        f=Path(td)/"disk"; f.write_bytes(os.urandom(65536))
        ok("disk-queue-depth-bench",j("disk-queue-depth-bench",f,"2","8","4096")["operations"]==8,q)
    ok("disk-iops-calculator",j("disk-iops-calculator","1000","2")["iops"]==500,q)
    ok("tcp-rtt-smoothing-calc","rto" in j("tcp-rtt-smoothing-calc",data="10 12 11 13"),q)
    ok("tcp-cwnd-growth-analyzer",len(j("tcp-cwnd-growth-analyzer","10","20","3")["history"])==3,q)
    ok("buffer-copy-throughput",j("buffer-copy-throughput","1024")[0]["bytes"]==1024,q)
    ok("zero-copy-splice-bench","supported" in j("zero-copy-splice-bench","4096"),q)
    ok("memory-leak-growth-rate",j("memory-leak-growth-rate",data="0 100\n1 120\n2 140\n")["bytes_per_time_unit"]==20,q)
    ok("resident-set-growth-chk",j("resident-set-growth-chk",data="100 120 140")["growing"] is True,q)
    ok("virtual-memory-size-view",j("virtual-memory-size-view",str(os.getpid()))["pid"]==os.getpid(),q)
    ok("garbage-collector-pause",j("garbage-collector-pause","1")["rounds"]==1,q)
    ok("allocator-fragmentation",j("allocator-fragmentation","100","160","80")["internal_fragmentation_bytes"]==60,q)
    ok("simd-vector-width-probe","architecture" in j("simd-vector-width-probe"),q)
    ok("neon-fp-pipeline-bench","supported" in j("neon-fp-pipeline-bench","1000"),q)
    ok("cpu-throttle-detector","cpus" in j("cpu-throttle-detector"),q)
    ok("thermal-governor-latency","changes" in j("thermal-governor-latency","0","1"),q)
    ok("power-consumption-model",j("power-consumption-model","4","1.5","0.5","4","2.5","0.5")["total_watts_model"]>0,q)
    ok("perf-script-filter-cli",p("perf-script-filter-cli","keep",data="drop\nkeep frame\n").stdout.strip()=="keep frame",q)
    dot=p("call-graph-dot-generator",data="main;a;b 2\nmain;a;c 1\n").stdout; ok("call-graph-dot-generator","digraph callgraph" in dot and '"main" -> "a"' in dot,q)
    if len(q)!=50 or len(set(q))!=50: raise AssertionError(f"expected 50 unique tests got {len(q)}/{len(set(q))}")
    print("PASS: 50/50 shard-26 functional commands")
if __name__=="__main__": main()
