"""Batch 2 of 4: Shards 11, 12, 13, 14, 16 (250 packages)
Each entry: (package_name, version, short_description)
"""

BATCH2_SHARDS = {
    "shard-11-compiler-toolchain-helpers": {
        "section": "devel",
        "category": "Compiler Toolchain & Binary Helpers",
        "description_prefix": "Binary analysis and compilation toolchain helper",
        "packages": [
            ("cxx-symbol-demangler", "1.0.0-1", "Itanium and MSVC C++ mangled symbol name demangler"),
            ("rust-symbol-demangle", "1.0.0-1", "Rust v0 and legacy mangled symbol demangler"),
            ("itanium-demangler", "1.0.0-1", "Itanium ABI C++ ABI mangling parser and formatter"),
            ("elf-section-size-calc", "1.0.0-1", "ELF section header table size and alignment auditor"),
            ("elf-relocation-dumper", "1.0.0-1", "ELF dynamic and static relocation entry dumper"),
            ("elf-dynamic-tags-view", "1.0.0-1", "ELF dynamic array DT_NEEDED DT_RPATH DT_RUNPATH viewer"),
            ("elf-string-table-cat", "1.0.0-1", "ELF .strtab and .dynstr string table extractor"),
            ("elf-symbol-versioning", "1.0.0-1", "GNU ELF symbol version definitions and requirements view"),
            ("elf-hash-table-chk", "1.0.0-1", "ELF sysv .hash and .gnu.hash bucket chain analyzer"),
            ("elf-gnu-hash-lookup", "1.0.0-1", "GNU Bloom filter fast symbol lookup simulator"),
            ("ar-archive-extractor", "1.0.0-1", "UNIX ar static library member extractor and indexer"),
            ("ranlib-index-viewer", "1.0.0-1", "archive symbol index table table-of-contents viewer"),
            ("nm-undefined-symbols", "1.0.0-1", "ELF undefined symbol resolution dependency scanner"),
            ("nm-defined-symbols", "1.0.0-1", "ELF exported symbol definitions and binding viewer"),
            ("strip-debug-symbols", "1.0.0-1", "DWARF debug sections identifier and stripper tool"),
            ("objcopy-binary-dump", "1.0.0-1", "ELF section raw binary dump and payload extractor"),
            ("llvm-bitcode-header", "1.0.0-1", "LLVM bitcode wrapper header and block parser"),
            ("llvm-ir-instruction-chk", "1.0.0-1", "LLVM IR assembly opcode and basic block validator"),
            ("wasm-header-parser", "1.0.0-1", "WebAssembly binary magic number and version parser"),
            ("wasm-section-lister", "1.0.0-1", "WebAssembly section IDs and payload size reporter"),
            ("wasm-opcode-disasm", "1.0.0-1", "WebAssembly code section instruction decoder"),
            ("dwarf-line-info-view", "1.0.0-1", "DWARF .debug_line source code file and line viewer"),
            ("dwarf-die-inspector", "1.0.0-1", "DWARF debugging information entry tree inspector"),
            ("ctf-type-data-parser", "1.0.0-1", "Compact C Type Format header and type table viewer"),
            ("btf-kernel-type-dump", "1.0.0-1", "BPF Type Format v1 header and type record analyzer"),
            ("pe-relocation-table", "1.0.0-1", "Portable Executable base relocation block parser"),
            ("coff-symbol-table-dump", "1.0.0-1", "COFF symbol table and auxiliary symbol dumper"),
            ("macho-dylib-id-view", "1.0.0-1", "Mach-O LC_ID_DYLIB and LC_LOAD_DYLIB command viewer"),
            ("macho-uuid-inspector", "1.0.0-1", "Mach-O LC_UUID binary identifier extractor"),
            ("macho-segment-calc", "1.0.0-1", "Mach-O __TEXT and __DATA segment size analyzer"),
            ("clang-ast-dump-filter", "1.0.0-1", "Clang AST JSON dump node filtering and search tool"),
            ("gcc-spec-file-parser", "1.0.0-1", "GCC compiler specs file compiler driver rule parser"),
            ("include-graph-builder", "1.0.0-1", "C/C++ #include preprocessor dependency graph builder"),
            ("c-preprocessor-macro", "1.0.0-1", "C preprocessor macro expansion visualizer"),
            ("c-token-counter", "1.0.0-1", "C99/C11 lexer token count and distribution profiler"),
            ("header-guard-validator", "1.0.0-1", "C/C++ header guard naming consistency validator"),
            ("pragma-once-checker", "1.0.0-1", "source tree header #pragma once usage checker"),
            ("static-assert-verify", "1.0.0-1", "compile-time constant expression evaluator simulator"),
            ("endian-byte-order-chk", "1.0.0-1", "binary integer endianness byte-swap validation tool"),
            ("calling-convention-chk", "1.0.0-1", "AAPCS64 calling convention argument register checker"),
            ("stack-frame-calculator", "1.0.0-1", "ARM64 stack frame layout and alignment calculator"),
            ("abi-alignment-checker", "1.0.0-1", "C struct field natural alignment and padding tool"),
            ("structure-padding-calc", "1.0.0-1", "data structure memory layout and hole visualizer"),
            ("vtable-layout-analyzer", "1.0.0-1", "C++ virtual method table pointer layout analyzer"),
            ("rtti-descriptor-view", "1.0.0-1", "C++ Run-Time Type Information type_info reader"),
            ("weak-symbol-finder", "1.0.0-1", "ELF symbol table weak symbol binding scanner"),
            ("hidden-visibility-chk", "1.0.0-1", "ELF symbol default vs hidden visibility auditor"),
            ("interposition-auditor", "1.0.0-1", "shared object symbol interposition conflict auditor"),
            ("linker-script-parser", "1.0.0-1", "GNU LD linker script SECTIONS and MEMORY parser"),
            ("symbol-alias-resolver", "1.0.0-1", "compiler symbol alias and strong/weak pairing tool"),
        ],
    },
    "shard-12-database-query-engines": {
        "section": "database",
        "category": "Database Engines & Query Processing",
        "description_prefix": "Embedded database and SQL processing engine",
        "packages": [
            ("duckdb-query-runner", "1.0.0-1", "analytical columnar SQL database CLI runner"),
            ("sqlite-fts5-tokenizer", "1.0.0-1", "SQLite Full Text Search 5 tokenizer query tool"),
            ("sqlite-json-query-cli", "1.0.0-1", "SQLite json_extract and json_each CLI processor"),
            ("sqlite-rbtree-visualizer", "1.0.0-1", "SQLite index B-tree balancing visualizer"),
            ("sqlite-b-tree-inspector", "1.0.0-1", "SQLite database file page header and cell parser"),
            ("sqlite-page-analyzer", "1.0.0-1", "SQLite page type freelist and overflow page auditor"),
            ("sqlite-vacuum-analyze", "1.0.0-1", "SQLite fragmented free page percentage calculator"),
            ("sqlite-pragma-dump", "1.0.0-1", "SQLite database PRAGMA configuration reporter"),
            ("sqlite-table-sizes", "1.0.0-1", "SQLite database per-table disk space usage analyzer"),
            ("sqlite-index-recommend", "1.0.0-1", "SQLite query execution plan index recommender"),
            ("sqlite-transaction-log", "1.0.0-1", "SQLite rollback journal header and change parser"),
            ("sqlite-blob-extractor", "1.0.0-1", "SQLite table BLOB column raw binary stream extractor"),
            ("sqlite-repair-corrupt", "1.0.0-1", "corrupt SQLite database raw text and row recovery"),
            ("rocksdb-sst-dump", "1.0.0-1", "RocksDB SSTable block format and index reader"),
            ("leveldb-log-inspector", "1.0.0-1", "LevelDB write-ahead log record and CRC checker"),
            ("lmdb-stat-analyzer", "1.0.0-1", "Lightning Memory-Mapped Database stat and page tool"),
            ("berkeleydb-hash-chk", "1.0.0-1", "Berkeley DB Hash and Btree file header parser"),
            ("redis-rdb-parser", "1.0.0-1", "Redis RDB snapshot file opcode and key-value parser"),
            ("redis-aof-rewriter", "1.0.0-1", "Redis Append-Only File RESP command parser"),
            ("redis-resp-encoder", "1.0.0-1", "Redis REdis Serialization Protocol RESP2/RESP3 encoder"),
            ("redis-resp-decoder", "1.0.0-1", "Redis RESP protocol parser and JSON translator"),
            ("memcached-text-proto", "1.0.0-1", "Memcached ASCII and binary protocol command tester"),
            ("cassandra-cql-parser", "1.0.0-1", "Cassandra CQL schema and keyspace syntax validator"),
            ("mongodb-extended-json", "1.0.0-1", "MongoDB Extended JSON v2 format to standard JSON tool"),
            ("postgresql-copy-stream", "1.0.0-1", "PostgreSQL COPY protocol text/binary stream formatter"),
            ("mysql-binlog-event-chk", "1.0.0-1", "MySQL binary log replication event header parser"),
            ("sql-dialect-converter", "1.0.0-1", "SQL dialect transpile helper Postgres SQLite MySQL"),
            ("sql-syntax-formatter", "1.0.0-1", "SQL query prettifier and indentation formatter"),
            ("sql-ast-visualizer", "1.0.0-1", "SQL query abstract syntax tree treeview generator"),
            ("sql-injection-tester", "1.0.0-1", "SQL query literal parameterization security checker"),
            ("db-migration-history", "1.0.0-1", "database migration version sequence gap detector"),
            ("db-schema-snapshot", "1.0.0-1", "database schema DDL snapshot differential generator"),
            ("db-foreign-key-chk", "1.0.0-1", "relational database foreign key constraint auditor"),
            ("db-orphan-records-chk", "1.0.0-1", "database orphaned child row consistency detector"),
            ("db-constraint-audit", "1.0.0-1", "database NOT NULL UNIQUE and CHECK constraint linter"),
            ("db-seed-data-gen", "1.0.0-1", "relational database deterministic mock row generator"),
            ("parquet-schema-viewer", "1.0.0-1", "Apache Parquet thrift file metadata schema viewer"),
            ("parquet-metadata-dump", "1.0.0-1", "Parquet row group and column chunk stats analyzer"),
            ("orc-file-footer-parser", "1.0.0-1", "Apache ORC file footer and stripe metadata parser"),
            ("arrow-ipc-validator", "1.0.0-1", "Apache Arrow IPC stream and record batch validator"),
            ("feather-file-inspect", "1.0.0-1", "Feather V1/V2 binary dataframe format inspector"),
            ("dbf-xbase-reader", "1.0.0-1", "dBase III/IV DBF table header and record extractor"),
            ("h2-database-export", "1.0.0-1", "H2 embedded SQL database script backup reader"),
            ("derby-log-analyzer", "1.0.0-1", "Apache Derby database transaction log analyzer"),
            ("timescaledb-hypertable", "1.0.0-1", "time-series database hypertable chunk size calculator"),
            ("influxdb-line-protocol", "1.0.0-1", "InfluxDB Line Protocol point measurement validator"),
            ("prometheus-tsdb-block", "1.0.0-1", "Prometheus TSDB 2-hour block meta.json inspector"),
            ("vector-embedding-index", "1.0.0-1", "high-dimensional vector cosine similarity indexer"),
            ("hnsw-distance-calc", "1.0.0-1", "Hierarchical Navigable Small World vector search tool"),
            ("faiss-index-header", "1.0.0-1", "FAISS vector index file header and dimensionality viewer"),
        ],
    },
    "shard-13-text-nlp-corpora": {
        "section": "text",
        "category": "Text Processing & Natural Language Corpora",
        "description_prefix": "Text tokenization and natural language processing tool",
        "packages": [
            ("unicode-codepoint-info", "1.0.0-1", "Unicode character property script and category lookup"),
            ("unicode-normalization", "1.0.0-1", "Unicode NFC NFD NFKC NFKD canonical normalizer"),
            ("utf8-byte-inspector", "1.0.0-1", "UTF-8 multi-byte encoding sequence boundary validator"),
            ("utf16-surrogate-pair", "1.0.0-1", "UTF-16 high and low surrogate pair calculator"),
            ("ascii-armor-encoder", "1.0.0-1", "Radix-64 ASCII armor stream encoder and checksum tool"),
            ("punycode-idna-decode", "1.0.0-1", "RFC 3492 Punycode algorithmic decoder and renderer"),
            ("regex-pcre2-tester", "1.0.0-1", "PCRE2 regular expression pattern test and capture cli"),
            ("regex-posix-matcher", "1.0.0-1", "POSIX Extended Regular Expression compliance tester"),
            ("regex-dfa-visualizer", "1.0.0-1", "regular expression deterministic finite automaton view"),
            ("word-frequency-counter", "1.0.0-1", "corpus word frequency distribution and rank counter"),
            ("character-ngram-gen", "1.0.0-1", "text character and subword n-gram frequency modeler"),
            ("token-stopword-filter", "1.0.0-1", "multilingual natural language stopword removal tool"),
            ("porter-stemmer-cli", "1.0.0-1", "Porter Stemming Algorithm morphological word stemmer"),
            ("snowball-stemmer-tool", "1.0.0-1", "Snowball multilingual algorithmic word stemmer"),
            ("soundex-phonetic-calc", "1.0.0-1", "Soundex phonetic indexing code calculator"),
            ("metaphone-phonetic-cli", "1.0.0-1", "Double Metaphone English phonetic encoding utility"),
            ("levenshtein-distance", "1.0.0-1", "Levenshtein edit distance string metric calculator"),
            ("jaro-winkler-similarity", "1.0.0-1", "Jaro-Winkler string similarity distance metric tool"),
            ("hamming-distance-calc", "1.0.0-1", "Hamming distance bit-flip and character diff metric"),
            ("diff-side-by-side", "1.0.0-1", "side-by-side two-column terminal text differential"),
            ("diff-unified-patcher", "1.0.0-1", "unified diff patch fuzz matching and hunk applicator"),
            ("diff-3way-merge-tool", "1.0.0-1", "three-way text file conflict merge reconciler"),
            ("wdiff-word-differ", "1.0.0-1", "word-by-word diff comparison for prose and text"),
            ("markdown-ast-generator", "1.0.0-1", "CommonMark markdown abstract syntax tree generator"),
            ("markdown-toc-builder", "1.0.0-1", "markdown document header table of contents generator"),
            ("markdown-table-prettifier", "1.0.0-1", "markdown pipe-delimited table column width aligner"),
            ("markdown-link-auditor", "1.0.0-1", "markdown internal and external URL hyperlink linter"),
            ("frontmatter-extractor", "1.0.0-1", "YAML TOML JSON document frontmatter header extractor"),
            ("latex-math-sanitizer", "1.0.0-1", "LaTeX mathematical formula syntax validator"),
            ("typst-document-linter", "1.0.0-1", "Typst typesetting markup syntax and layout linter"),
            ("asciidoc-section-view", "1.0.0-1", "AsciiDoc document structure and section tree linter"),
            ("manpage-troff-linter", "1.0.0-1", "UNIX manual page groff man macro syntax validator"),
            ("groff-formatter-lite", "1.0.0-1", "lightweight troff roff typesetting macro processor"),
            ("spellcheck-hunspell", "1.0.0-1", "Hunspell affix and dictionary spell checking engine"),
            ("aspell-word-filter", "1.0.0-1", "Aspell phonetic spell checking word suggestion tool"),
            ("syllable-counter-cli", "1.0.0-1", "English word syllable count heuristic estimator"),
            ("readability-flesch", "1.0.0-1", "Flesch Reading Ease and Kincaid grade level index"),
            ("text-summarizer-lex", "1.0.0-1", "lexical frequency extractive text summarizer"),
            ("line-wrap-hyphenator", "1.0.0-1", "Knuth-Liang paragraph text wrapping and hyphenator"),
            ("column-table-justifier", "1.0.0-1", "plain text multi-column whitespace table aligner"),
            ("ansi-color-stripper", "1.0.0-1", "terminal ANSI escape code and color sequence remover"),
            ("ansi-art-renderer", "1.0.0-1", "ANSI and ASCII art terminal canvas validator"),
            ("ascii-box-drawing", "1.0.0-1", "Unicode box drawing border and panel generator"),
            ("slugify-text-cli", "1.0.0-1", "URL slug generator with accent diacritic stripping"),
            ("case-camel-snake-kebab", "1.0.0-1", "programming identifier casing converter camel snake kebab"),
            ("rot47-cipher-tool", "1.0.0-1", "ROT47 ASCII printable character transposition tool"),
            ("bidi-text-reverser", "1.0.0-1", "bidirectional Unicode text ordering visualizer"),
            ("zero-width-char-chk", "1.0.0-1", "invisible zero-width space and homoglyph scanner"),
            ("line-ending-dos2unix", "1.0.0-1", "CRLF to LF line ending converter and detector"),
            ("tab-space-converter", "1.0.0-1", "tab-to-spaces expand and unexpand formatting filter"),
        ],
    },
    "shard-14-image-media-audio": {
        "section": "graphics",
        "category": "Media Formats & Audio-Visual Processing",
        "description_prefix": "Media header parser and audiovisual engineering utility",
        "packages": [
            ("png-chunk-parser", "1.0.0-1", "Portable Network Graphics chunk structure and CRC validator"),
            ("png-ihdr-analyzer", "1.0.0-1", "PNG IHDR dimensions bit-depth and color type reader"),
            ("png-crush-optimizer", "1.0.0-1", "lossless PNG deflation filter strategy evaluator"),
            ("jpeg-exif-stripper", "1.0.0-1", "JPEG Exchangeable Image File metadata remover"),
            ("jpeg-marker-parser", "1.0.0-1", "JPEG SOF0 SOI EOI APP0 marker segment inspector"),
            ("jpeg-progressive-chk", "1.0.0-1", "progressive vs baseline JPEG scan order detector"),
            ("gif-frame-counter", "1.0.0-1", "GIF89a graphics control extension animated frame counter"),
            ("gif-palette-extractor", "1.0.0-1", "GIF global and local color table palette viewer"),
            ("webp-vp8-chunk-view", "1.0.0-1", "WebP RIFF container VP8 VP8L VP8X chunk reader"),
            ("avif-box-inspector", "1.0.0-1", "AV1 Image File Format ISOBMFF box item parser"),
            ("heif-item-parser", "1.0.0-1", "High Efficiency Image File meta iref iprp box reader"),
            ("bmp-dib-header-dump", "1.0.0-1", "Windows Bitmap BITMAPINFOHEADER DIB header parser"),
            ("ico-icon-dir-parser", "1.0.0-1", "Windows Icon ICONDIR and ICONDIRENTRY image parser"),
            ("tga-header-analyzer", "1.0.0-1", "Truevision TGA header color map and pixel depth tool"),
            ("tiff-ifd-inspector", "1.0.0-1", "TIFF Image File Directory tag count and offset reader"),
            ("svg-path-optimizer", "1.0.0-1", "SVG path data decimal precision reducer and cleaner"),
            ("svg-viewbox-fixer", "1.0.0-1", "SVG viewBox width height coordinate space normalizer"),
            ("svg-xml-sanitizer", "1.0.0-1", "SVG XML malicious script and entity reference cleaner"),
            ("color-hex-rgb-hsl", "1.0.0-1", "color format converter HEX RGB HSL HSV CMYK"),
            ("color-palette-generator", "1.0.0-1", "complementary and triadic harmonic color palette tool"),
            ("color-contrast-wcag", "1.0.0-1", "WCAG 2.1 accessible color luminance contrast ratio calc"),
            ("lut-color-cube-parser", "1.0.0-1", "3D Look-Up Table .cube file format validator"),
            ("histogram-image-cli", "1.0.0-1", "image red green blue channel luminance histogram"),
            ("pixel-aspect-ratio", "1.0.0-1", "digital video pixel aspect ratio to display aspect ratio"),
            ("image-dimension-probe", "1.0.0-1", "fast zero-decode image dimension and format detector"),
            ("wav-riff-chunk-dump", "1.0.0-1", "WAV RIFF fmt data chunk structure analyzer"),
            ("wav-fmt-spec-checker", "1.0.0-1", "WAV audio sample rate bit depth channel count inspector"),
            ("flac-metadata-block", "1.0.0-1", "Free Lossless Audio Codec METADATA_BLOCK_STREAMINFO view"),
            ("mp3-id3v2-tag-dump", "1.0.0-1", "MP3 ID3v2.3/ID3v2.4 frame header and text tag parser"),
            ("mp3-frame-sync-chk", "1.0.0-1", "MPEG audio frame synchronization word and bitrate tool"),
            ("ogg-page-header-dump", "1.0.0-1", "Ogg bitstream transport framing page header reader"),
            ("opus-head-packet-chk", "1.0.0-1", "OpusHead identification header and preskip calculator"),
            ("vorbis-comment-reader", "1.0.0-1", "Ogg Vorbis user comment vendor string field extractor"),
            ("aac-adts-header-dump", "1.0.0-1", "Advanced Audio Coding ADTS synchronization header dump"),
            ("midi-track-event-view", "1.0.0-1", "Standard MIDI File MThd MTrk delta time event parser"),
            ("pcm-sample-rate-conv", "1.0.0-1", "PCM raw audio sample rate and bit depth calculator"),
            ("audio-duration-calc", "1.0.0-1", "uncompressed audio file duration from byte length calc"),
            ("audio-bitrate-sampler", "1.0.0-1", "constant vs variable bitrate distribution analyzer"),
            ("ffmpeg-probe-lite", "1.0.0-1", "multimedia container stream audio/video track prober"),
            ("mp4-moov-atom-parser", "1.0.0-1", "MPEG-4 Part 14 ftyp moov mvhd trak atom parser"),
            ("mkv-ebml-header-dump", "1.0.0-1", "Matroska EBML document header and track UID reader"),
            ("avi-riff-list-parser", "1.0.0-1", "Audio Video Interleave RIFF LIST hdrl movi parser"),
            ("subtitle-srt-time-shift", "1.0.0-1", "SubRip SRT subtitle timestamp offset shifting tool"),
            ("subtitle-vtt-validator", "1.0.0-1", "WebVTT cue timing and caption structure validator"),
            ("yuv-frame-calculator", "1.0.0-1", "raw YUV 4:2:0 planar frame buffer size calculator"),
            ("video-fps-timecode", "1.0.0-1", "video frame rate SMPTE drop-frame timecode converter"),
            ("dpi-calculator-cli", "1.0.0-1", "display dots-per-inch and physical screen dimension calc"),
            ("aspect-ratio-reducer", "1.0.0-1", "screen resolution to simplified aspect ratio reducer"),
            ("color-temperature-calc", "1.0.0-1", "Kelvin color temperature to approximate RGB calc"),
            ("bayer-pattern-matrix", "1.0.0-1", "camera raw Bayer color filter array pattern inspector"),
        ],
    },
    "shard-16-math-scientific-computing": {
        "section": "math",
        "category": "Scientific Computing & Discrete Mathematics",
        "description_prefix": "Scientific calculation and numerical algorithm engine",
        "packages": [
            ("bigint-modular-power", "1.0.0-1", "arbitrary-precision modular exponentiation calculator"),
            ("bigint-extended-gcd", "1.0.0-1", "Extended Euclidean algorithm Bezout identity solver"),
            ("bigfloat-sqrt-calc", "1.0.0-1", "arbitrary-precision square root via Newton-Raphson"),
            ("bigfloat-pi-chudnovsky", "1.0.0-1", "Chudnovsky algorithm arbitrary precision Pi generator"),
            ("matrix-determinant-2d", "1.0.0-1", "2x2 and NxN matrix determinant algebraic solver"),
            ("matrix-inverse-3d", "1.0.0-1", "matrix Gauss-Jordan elimination inversion tool"),
            ("matrix-eigen-evaluator", "1.0.0-1", "symmetric matrix eigenvalue power iteration estimator"),
            ("vector-dot-cross-prod", "1.0.0-1", "3D vector dot product cross product and norm calculator"),
            ("linear-regression-ols", "1.0.0-1", "Ordinary Least Squares slope and intercept calculator"),
            ("polynomial-root-finder", "1.0.0-1", "polynomial synthetic division and real root finder"),
            ("runge-kutta-integrator", "1.0.0-1", "RK4 fourth-order Runge-Kutta differential solver"),
            ("simpson-integral-calc", "1.0.0-1", "composite Simpson numerical definite integral solver"),
            ("fft-fourier-transform", "1.0.0-1", "Cooley-Tukey Radix-2 Fast Fourier Transform tool"),
            ("dft-discrete-fourier", "1.0.0-1", "Discrete Fourier Transform discrete frequency analyzer"),
            ("complex-number-calc", "1.0.0-1", "complex arithmetic magnitude phase Euler polar form"),
            ("quaternion-rotation", "1.0.0-1", "3D quaternion Hamilton product and spatial rotation"),
            ("normal-distribution-cdf", "1.0.0-1", "Gaussian standard normal cumulative distribution"),
            ("poisson-prob-calc", "1.0.0-1", "Poisson probability mass function and interval solver"),
            ("binomial-distribution", "1.0.0-1", "binomial coefficient and Bernoulli trial calculator"),
            ("chi-square-statistic", "1.0.0-1", "Chi-square goodness-of-fit contingency test tool"),
            ("student-t-distribution", "1.0.0-1", "Student t-distribution two-tailed p-value evaluator"),
            ("standard-deviation-calc", "1.0.0-1", "sample variance and standard deviation calculator"),
            ("covariance-matrix-cli", "1.0.0-1", "multivariate dataset covariance matrix calculator"),
            ("spearman-rank-calc", "1.0.0-1", "Spearman rank correlation coefficient calculator"),
            ("pearson-correlation", "1.0.0-1", "Pearson product-moment correlation coefficient tool"),
            ("k-means-clustering-cli", "1.0.0-1", "K-Means Lloyd clustering centroid classifier"),
            ("dijkstra-shortest-path", "1.0.0-1", "Dijkstra weighted graph shortest path algorithm"),
            ("a-star-path-finder", "1.0.0-1", "A* heuristic search 2D grid pathfinding solver"),
            ("bellman-ford-detector", "1.0.0-1", "Bellman-Ford negative weight cycle detector"),
            ("topological-sorter", "1.0.0-1", "Directed Acyclic Graph Kahn topological sort engine"),
            ("bipartite-graph-match", "1.0.0-1", "Hopcroft-Karp maximum bipartite matching algorithm"),
            ("spanning-tree-kruskal", "1.0.0-1", "Kruskal Minimum Spanning Tree disjoint-set solver"),
            ("convex-hull-graham", "1.0.0-1", "Graham scan 2D point cloud convex hull calculator"),
            ("voronoi-diagram-cli", "1.0.0-1", "2D planar Voronoi partition cell vertex generator"),
            ("delaunay-triangulate", "1.0.0-1", "Bowyer-Watson 2D Delaunay triangulation tool"),
            ("geodesic-distance-vin", "1.0.0-1", "Vincenty inverse geodesic ellipsoid distance tool"),
            ("haversine-distance-cli", "1.0.0-1", "Haversine great-circle spherical distance calculator"),
            ("utm-lat-long-converter", "1.0.0-1", "Universal Transverse Mercator GPS coordinate converter"),
            ("coordinate-proj-proj4", "1.0.0-1", "cartographic coordinate transformation helper"),
            ("astronomical-julian", "1.0.0-1", "Julian Day and Modified Julian Date astronomical calc"),
            ("sidereal-time-calc", "1.0.0-1", "Greenwich Mean Sidereal Time astronomical calculator"),
            ("solar-zenith-angle", "1.0.0-1", "solar elevation and azimuth zenith angle calculator"),
            ("temperature-scale-conv", "1.0.0-1", "Celsius Fahrenheit Kelvin Rankine Delisle converter"),
            ("pressure-unit-calc", "1.0.0-1", "Pascal Bar Atmosphere Torr PSI pressure converter"),
            ("energy-joule-kwh-conv", "1.0.0-1", "Joule Watt-hour Calorie BTU energy converter"),
            ("speed-of-sound-calc", "1.0.0-1", "speed of sound in dry air by temperature calculator"),
            ("doppler-shift-calc", "1.0.0-1", "Doppler frequency shift acoustic and RF calculator"),
            ("signal-to-noise-ratio", "1.0.0-1", "Signal-to-Noise Ratio and decibel power calculator"),
            ("boolean-logic-solver", "1.0.0-1", "boolean logic expression truth table and SAT solver"),
            ("truth-table-generator", "1.0.0-1", "propositional logic formula full truth table matrix"),
        ],
    },
}
