"""Batch 3 of 4: Shards 17, 18, 19, 20, 21 (250 packages)
Each entry: (package_name, version, short_description)
"""

BATCH3_SHARDS = {
    "shard-17-android-bionic-platform": {
        "section": "admin",
        "category": "Android Bionic & Subsystem Platform",
        "description_prefix": "Android Bionic and runtime platform utility",
        "packages": [
            ("android-property-parser", "1.0.0-1", "Android __system_property_get memory structure parser"),
            ("getprop-filter-tool", "1.0.0-1", "Android system properties key filtering and JSON dump"),
            ("setprop-format-checker", "1.0.0-1", "Android system property key name and value syntax linter"),
            ("logcat-tag-filter", "1.0.0-1", "Android logcat binary logger buffer tag priority filter"),
            ("logcat-json-formatter", "1.0.0-1", "Android logcat stream to NDJSON event converter"),
            ("logcat-timestamp-align", "1.0.0-1", "Android logcat epoch millisecond timestamp aligner"),
            ("binder-transact-tracer", "1.0.0-1", "Android Binder IPC transaction code and interface view"),
            ("ashmem-region-auditor", "1.0.0-1", "Android Anonymous Shared Memory ashmem size inspector"),
            ("ion-memory-alloc-view", "1.0.0-1", "Android ION memory allocator client heap status view"),
            ("dmabuf-heap-inspector", "1.0.0-1", "Linux dma-buf heap allocations and buffer sharing tool"),
            ("selinux-context-check", "1.0.0-1", "SELinux file security context u:r:s0 syntax checker"),
            ("selinux-avc-denial-log", "1.0.0-1", "SELinux Access Vector Cache denial audit parser"),
            ("sepolicy-rule-search", "1.0.0-1", "Android compiled sepolicy TE allow rule search engine"),
            ("service-list-auditor", "1.0.0-1", "Android ServiceManager registered IBinder service audit"),
            ("package-setting-parser", "1.0.0-1", "Android packages.xml permission and package parser"),
            ("package-signing-v1-chk", "1.0.0-1", "Android APK Signature Scheme v1 JAR manifest check"),
            ("package-signing-v2-chk", "1.0.0-1", "Android APK Signature Scheme v2 block 0x7109871a check"),
            ("package-signing-v3-chk", "1.0.0-1", "Android APK Signature Scheme v3 key rotation checker"),
            ("package-signing-v4-chk", "1.0.0-1", "Android APK Signature Scheme v4 Merkle tree file check"),
            ("dex-header-inspector", "1.0.0-1", "Dalvik Executable format 035-039 header magic analyzer"),
            ("dex-map-list-parser", "1.0.0-1", "DEX file map_list item offset and section size tool"),
            ("dex-string-id-dump", "1.0.0-1", "DEX string_ids and string_data_item MUTF-8 extractor"),
            ("dex-type-id-parser", "1.0.0-1", "DEX type_ids type descriptor table decompiler"),
            ("dex-proto-id-view", "1.0.0-1", "DEX proto_ids method prototype parameter list viewer"),
            ("dex-field-id-dump", "1.0.0-1", "DEX field_ids class field definition list viewer"),
            ("dex-method-id-dump", "1.0.0-1", "DEX method_ids method table and signature inspector"),
            ("dex-class-def-viewer", "1.0.0-1", "DEX class_def access flags and superclass inspector"),
            ("cdex-compact-header", "1.0.0-1", "Compact DEX CDEX header and shared data section view"),
            ("vdex-verifier-header", "1.0.0-1", "Android VDEX verified DEX container header inspector"),
            ("oat-runtime-header", "1.0.0-1", "Android OAT ahead-of-time compiled ELF header parser"),
            ("art-image-header-dump", "1.0.0-1", "Android ART boot.art image header and object space view"),
            ("apex-manifest-parser", "1.0.0-1", "Android APEX container apex_manifest.json/pb parser"),
            ("apex-payload-inspector", "1.0.0-1", "Android APEX ext4/erofs loopback payload inspector"),
            ("dalvik-bytecode-check", "1.0.0-1", "Dalvik bytecode opcode table and register count linter"),
            ("bionic-pthread-key-chk", "1.0.0-1", "Bionic C library pthread_key_create limit analyzer"),
            ("bionic-futex-flags", "1.0.0-1", "Bionic private futex operation flags decode helper"),
            ("android-cmd-caller", "1.0.0-1", "Android framework cmd interactive command line wrapper"),
            ("am-intent-uri-builder", "1.0.0-1", "Android ActivityManager intent URI syntax generator"),
            ("pm-dump-permissions", "1.0.0-1", "Android PackageManager permission tree and group dump"),
            ("dumpsys-battery-parse", "1.0.0-1", "Android dumpsys battery level voltage and temp parser"),
            ("dumpsys-meminfo-parse", "1.0.0-1", "dumpsys meminfo native dalvik graphics heap analyzer"),
            ("dumpsys-cpuinfo-parse", "1.0.0-1", "dumpsys cpuinfo user system iowait distribution tool"),
            ("dumpsys-window-parser", "1.0.0-1", "dumpsys window display orientation and bounds parser"),
            ("settings-db-query-cli", "1.0.0-1", "Android settings system secure global table parser"),
            ("keystore-key-alias-chk", "1.0.0-1", "Android KeyStore hardware-backed key alias checker"),
            ("keymaster-tag-parser", "1.0.0-1", "Android KeyMaster/KeyMint authorization tag decoder"),
            ("input-event-code-view", "1.0.0-1", "Linux /dev/input/event EV_KEY EV_ABS event code parser"),
            ("vold-mount-inspector", "1.0.0-1", "Android Volume Daemon storage mount state inspector"),
            ("recovery-fstab-parser", "1.0.0-1", "Android recovery.fstab block device mount points view"),
            ("boot-image-v4-header", "1.0.0-1", "Android boot image v3/v4 kernel ramdisk header parser"),
        ],
    },
    "shard-18-code-lint-analysis": {
        "section": "devel",
        "category": "Code Quality & Static Analysis",
        "description_prefix": "Static analysis and source code auditing utility",
        "packages": [
            ("cyclomatic-complexity", "1.0.0-1", "McCabe cyclomatic complexity metric calculator for code"),
            ("halstead-metric-calc", "1.0.0-1", "Halstead software science vocabulary and volume metric"),
            ("lines-of-code-counter", "1.0.0-1", "blank comment and physical source lines of code count"),
            ("sloccount-lightweight", "1.0.0-1", "multi-language source line counter and effort model"),
            ("maintainability-index", "1.0.0-1", "Maintainability Index MI software quality score tool"),
            ("cognitive-complexity", "1.0.0-1", "cognitive code comprehension difficulty metric engine"),
            ("dead-code-finder", "1.0.0-1", "unused function and variable static analysis detector"),
            ("unreachable-code-chk", "1.0.0-1", "control flow graph dead basic block and branch linter"),
            ("cyclomatic-depth-tree", "1.0.0-1", "nested control structure nesting depth visualizer"),
            ("switch-fallthrough-chk", "1.0.0-1", "switch statement missing break fallthrough auditor"),
            ("null-pointer-deref-chk", "1.0.0-1", "static null pointer dereference potential warning tool"),
            ("buffer-overflow-pattern", "1.0.0-1", "unsafe C standard library strcpy sprintf pattern finder"),
            ("format-string-vuln-chk", "1.0.0-1", "printf format string vulnerability static pattern audit"),
            ("integer-overflow-chk", "1.0.0-1", "signed integer arithmetic overflow heuristic detector"),
            ("uninitialized-var-chk", "1.0.0-1", "uninitialized stack variable read heuristic scanner"),
            ("memory-leak-pattern", "1.0.0-1", "malloc without free paired allocation trace heuristic"),
            ("resource-leak-detector", "1.0.0-1", "unclosed file descriptor and socket leak pattern linter"),
            ("race-condition-pattern", "1.0.0-1", "unprotected shared state multi-threading pattern check"),
            ("lock-inversion-finder", "1.0.0-1", "mutex acquisition ordering and inversion cycle finder"),
            ("deadlock-cycle-checker", "1.0.0-1", "resource allocation graph deadlock cycle detector"),
            ("dep-graph-generator", "1.0.0-1", "module dependency graph generator in Graphviz DOT format"),
            ("circular-dep-detector", "1.0.0-1", "circular software component import cycle detector"),
            ("unused-include-finder", "1.0.0-1", "C/C++ redundant #include header directive detector"),
            ("header-dependency-tree", "1.0.0-1", "header file inclusion depth and tree visualization"),
            ("c-symbol-coverage", "1.0.0-1", "C header function declaration vs implementation diff"),
            ("py-ast-linter-lite", "1.0.0-1", "Python abstract syntax tree syntax and safety checker"),
            ("js-ast-syntax-checker", "1.0.0-1", "ECMAScript/JavaScript syntax and strict mode linter"),
            ("rust-syntax-validator", "1.0.0-1", "Rust language tokens and macro bracket matching linter"),
            ("go-ast-token-scanner", "1.0.0-1", "Go source file package imports and struct field check"),
            ("shell-posix-validator", "1.0.0-1", "POSIX sh compliance and non-portable bashism detector"),
            ("makefile-syntax-linter", "1.0.0-1", "Makefile tab indentation and rule prerequisite linter"),
            ("cmake-syntax-checker", "1.0.0-1", "CMakeLists.txt command arguments and policy validator"),
            ("meson-build-validator", "1.0.0-1", "meson.build project and dependency syntax linter"),
            ("ninja-graph-visualize", "1.0.0-1", "build.ninja dependency rule and edge DAG visualizer"),
            ("pkgconfig-file-linter", "1.0.0-1", "pkg-config .pc file Libs Cflags syntax validator"),
            ("api-version-diff-tool", "1.0.0-1", "API public interface additions and removals differ"),
            ("semver-bump-calculator", "1.0.0-1", "Semantic Versioning MAJOR MINOR PATCH bump recommender"),
            ("changelog-linter-tool", "1.0.0-1", "Keep a Changelog standard format markdown linter"),
            ("license-spdx-checker", "1.0.0-1", "SPDX-License-Identifier expression syntax validator"),
            ("license-compatibility", "1.0.0-1", "open-source software license compatibility matrix tool"),
            ("author-attribution-chk", "1.0.0-1", "git commit history author email format validator"),
            ("copyright-year-updater", "1.0.0-1", "source header copyright notice year range validator"),
            ("comment-ratio-metric", "1.0.0-1", "code-to-comment ratio and documentation density score"),
            ("todo-fixme-collector", "1.0.0-1", "TODO FIXME HACK XXX code annotation parser and reporter"),
            ("magic-number-detector", "1.0.0-1", "unnamed numerical constant magic number detector"),
            ("variable-naming-linter", "1.0.0-1", "identifier naming convention consistency checker"),
            ("function-length-linter", "1.0.0-1", "excessive function line length and complexity alert"),
            ("nesting-depth-limiter", "1.0.0-1", "excessive block nesting level threshold analyzer"),
            ("duplicate-code-clone", "1.0.0-1", "token-based duplicate code block clone detector"),
            ("refactoring-advisor", "1.0.0-1", "code smell detection and automated refactor advisor"),
        ],
    },
    "shard-19-archive-backup-sync": {
        "section": "utils",
        "category": "Archive Formats & Differential Backup",
        "description_prefix": "Archive file format and differential backup utility",
        "packages": [
            ("tar-header-validator", "1.0.0-1", "POSIX ustar and GNU tar header block checksum tool"),
            ("tar-gnu-longlink-chk", "1.0.0-1", "tar ././@LongLink path overflow entry inspector"),
            ("tar-pax-extended-chk", "1.0.0-1", "POSIX.1-2001 pax extended header attribute parser"),
            ("tar-sparse-header-chk", "1.0.0-1", "GNU tar sparse file map header and offset viewer"),
            ("cpio-crc-format-dump", "1.0.0-1", "cpio CRC format file magic and inode table parser"),
            ("cpio-odc-format-dump", "1.0.0-1", "cpio portable old ASCII format header decoder"),
            ("cpio-newc-header-chk", "1.0.0-1", "cpio SVR4 new ASCII format header validator"),
            ("ar-bsd-variant-parser", "1.0.0-1", "BSD ar archive #1/ extended file name parser"),
            ("ar-gnu-variant-parser", "1.0.0-1", "GNU ar archive // long file name table parser"),
            ("zip-eocd-locator-cli", "1.0.0-1", "ZIP End of Central Directory record offset locator"),
            ("zip-cd-record-viewer", "1.0.0-1", "ZIP Central Directory file header table inspector"),
            ("zip-extra-field-parse", "1.0.0-1", "ZIP extra field header IDs and payloads parser"),
            ("zip64-locator-parser", "1.0.0-1", "ZIP64 End of Central Directory record locator tool"),
            ("sevenzip-signature-chk", "1.0.0-1", "7z archive 7z\\xBC\\xAF\\x27\\x1C signature and version tool"),
            ("sevenzip-header-view", "1.0.0-1", "7z stream folder coders and unpack sizes reader"),
            ("rar5-header-validator", "1.0.0-1", "RAR 5.0 archive signature and block header parser"),
            ("cab-folder-extractor", "1.0.0-1", "Microsoft Cabinet CFHEADER and CFFOLDER viewer"),
            ("iso-rockridge-parser", "1.0.0-1", "ISO 9660 Rock Ridge interchange protocol parser"),
            ("iso-joliet-ext-parser", "1.0.0-1", "ISO 9660 Joliet Unicode file system extension parser"),
            ("wim-header-inspector", "1.0.0-1", "Windows Imaging Format WIMHEADER and XML data reader"),
            ("squashfs-inode-table", "1.0.0-1", "SquashFS inode lookup table and fragment parser"),
            ("ext4-dump-restore-chk", "1.0.0-1", "ext4 dump/restore tape archive format inspector"),
            ("rdiff-delta-generator", "1.0.0-1", "binary file delta differential patch generator"),
            ("rdiff-patch-applier", "1.0.0-1", "binary differential delta patch application tool"),
            ("rsync-checksum-block", "1.0.0-1", "rsync rolling checksum and MD4/MD5 block calculator"),
            ("rsync-rolling-hash", "1.0.0-1", "Adler-32 inspired rsync fast sliding window hash"),
            ("adler32-rolling-calc", "1.0.0-1", "rolling Adler-32 incremental checksum calculator"),
            ("rabin-karp-chunker", "1.0.0-1", "Rabin-Karp fingerprint rolling hash chunking tool"),
            ("content-defined-chunk", "1.0.0-1", "Content-Defined Chunking CDC deduplication tool"),
            ("fastcdc-chunker-cli", "1.0.0-1", "FastCDC sub-chunk boundary chunking algorithm tool"),
            ("backup-catalog-verify", "1.0.0-1", "backup manifest database catalog consistency checker"),
            ("backup-retention-calc", "1.0.0-1", "Grandfather-Father-Son backup retention schedule tool"),
            ("snapshot-differential", "1.0.0-1", "directory tree snapshot added modified deleted diff"),
            ("dir-tree-hasher-fast", "1.0.0-1", "fast parallel directory tree deterministic Merkle hasher"),
            ("mtree-specification-gen", "1.0.0-1", "BSD mtree file hierarchy specification generator"),
            ("mtree-validator-tool", "1.0.0-1", "BSD mtree filesystem tree validation and auditor"),
            ("dar-disk-archiver-chk", "1.0.0-1", "DAR Disk ARchive slice header and catalog reader"),
            ("afio-archive-linter", "1.0.0-1", "afio crash-tolerant cpio archive format validator"),
            ("pax-archive-validator", "1.0.0-1", "POSIX pax interchange archive format validator"),
            ("xar-xml-toc-extractor", "1.0.0-1", "eXtensible ARchive XAR XML Table of Contents tool"),
            ("chm-archive-header-chk", "1.0.0-1", "Compiled HTML Help ITSF file header and directory tool"),
            ("deb-ar-data-splitter", "1.0.0-1", "Debian deb package debian-binary control data splitter"),
            ("rpm-lead-header-parser", "1.0.0-1", "RPM package lead and header structure inspector"),
            ("apk-zip-comment-tool", "1.0.0-1", "Android APK End of Central Directory comment reader"),
            ("vhd-footer-inspector", "1.0.0-1", "Virtual Hard Disk VHD fixed/dynamic footer reader"),
            ("qcow2-header-parser", "1.0.0-1", "QEMU Copy-On-Write qcow2 header and L1 table reader"),
            ("vmdk-descriptor-view", "1.0.0-1", "VMware VMDK monolithic sparse descriptor viewer"),
            ("raw-disk-image-resizer", "1.0.0-1", "raw sector image boundary calculation and expander"),
            ("sparse-image-converter", "1.0.0-1", "Android sparse image format to raw sector converter"),
            ("simg2img-ocean-cli", "1.0.0-1", "Android sparse image unsparse conversion utility"),
        ],
    },
    "shard-20-security-audit-forensics": {
        "section": "admin",
        "category": "Security Forensics & Incident Response",
        "description_prefix": "Security forensic analysis and incident response tool",
        "packages": [
            ("pcap-dns-query-extract", "1.0.0-1", "extract DNS query questions and replies from PCAP files"),
            ("pcap-http-uri-extract", "1.0.0-1", "extract HTTP requests URLs User-Agents from PCAP"),
            ("pcap-tls-client-hello", "1.0.0-1", "extract TLS ClientHello ciphers and SNI from PCAP"),
            ("pcap-credential-finder", "1.0.0-1", "cleartext credential detector in network capture files"),
            ("pcap-icmp-tunnel-chk", "1.0.0-1", "ICMP payload covert channel data exfiltration checker"),
            ("raw-memory-string-dump", "1.0.0-1", "raw process memory dump ASCII and UTF-16 string parser"),
            ("volatility-profile-chk", "1.0.0-1", "memory forensic profile banner and symbol table check"),
            ("page-table-walk-tool", "1.0.0-1", "virtual memory page table descriptor walk simulator"),
            ("kernel-module-sig-chk", "1.0.0-1", "Linux kernel .ko module cryptographic signature checker"),
            ("rootkit-symbol-search", "1.0.0-1", "kernel hooking and sys_call_table address inspector"),
            ("hidden-process-finder", "1.0.0-1", "cross-reference /proc PIDs with kill(0) signal checks"),
            ("proc-maps-anomaly-chk", "1.0.0-1", "executable heap and stack memory anomaly detector"),
            ("mem-injection-scanner", "1.0.0-1", "process memory injection and shellcode pattern scanner"),
            ("code-cave-finder-elf", "1.0.0-1", "ELF executable section padding code cave detector"),
            ("elf-got-overwrite-chk", "1.0.0-1", "Global Offset Table integrity and overwrite detector"),
            ("elf-plt-hook-detector", "1.0.0-1", "Procedure Linkage Table redirection hook detector"),
            ("ptrace-anti-debug-chk", "1.0.0-1", "ptrace PTRACE_TRACEME anti-debugging pattern detector"),
            ("process-environment-diff", "1.0.0-1", "process environment variable deviation detector"),
            ("ld-preload-auditor", "1.0.0-1", "dynamic linker LD_PRELOAD library interception auditor"),
            ("ld-so-preload-clean", "1.0.0-1", "/etc/ld.so.preload malicious library injection detector"),
            ("binary-entropy-graph", "1.0.0-1", "sliding-window binary file byte entropy grapher"),
            ("packed-executable-chk", "1.0.0-1", "software packer and crypter heuristic detector"),
            ("upx-header-unpacker", "1.0.0-1", "UPX compressed executable header and magic inspector"),
            ("pe-rich-header-hasher", "1.0.0-1", "PE executable Rich header compiler checksum hasher"),
            ("imphash-calculator", "1.0.0-1", "PE import table hash imphash malicious cluster tool"),
            ("fuzzy-ssdeep-hasher", "1.0.0-1", "Context Triggered Piecewise Hashing ssdeep fuzzy tool"),
            ("fuzzy-tlsh-calculator", "1.0.0-1", "Trend Micro Locality Sensitive Hash TLSH similarity tool"),
            ("anti-vm-artifact-chk", "1.0.0-1", "hypervisor and sandbox hardware artifact detector"),
            ("sandbox-detection-chk", "1.0.0-1", "uptime and user interaction analysis evasion detector"),
            ("threat-intel-ip-parser", "1.0.0-1", "threat intelligence IP indicator of compromise parser"),
            ("ioc-stix-json-parser", "1.0.0-1", "STIX 2.1 structured threat information expression tool"),
            ("snort-rule-validator", "1.0.0-1", "Snort/Suricata intrusion detection rule syntax linter"),
            ("suricata-rule-tester", "1.0.0-1", "Suricata network threat detection signature linter"),
            ("sigma-rule-converter", "1.0.0-1", "Sigma generic log signature format syntax validator"),
            ("windows-event-evtx-chk", "1.0.0-1", "Windows Event Log .evtx file header chunk validator"),
            ("syslog-auth-failure", "1.0.0-1", "system authentication log brute force failure parser"),
            ("pam-auth-audit-trail", "1.0.0-1", "Linux PAM authentication log audit sequence analyzer"),
            ("sudoers-file-validator", "1.0.0-1", "sudoers privilege specification and NOPASSWD linter"),
            ("suid-binary-matrix", "1.0.0-1", "setuid and setgid binary GTFOBins capability matrix"),
            ("shadow-password-audit", "1.0.0-1", "/etc/shadow weak password hash algorithm auditor"),
            ("ssh-authorized-keys-chk", "1.0.0-1", "SSH authorized_keys command restrictions and key sizes"),
            ("ssh-known-hosts-hash", "1.0.0-1", "SSH known_hosts hashed hostname lookup and verifier"),
            ("gpg-keyring-auditor", "1.0.0-1", "GPG public keyring weak DSA/RSA-1024 key auditor"),
            ("ssl-tls-poodle-tester", "1.0.0-1", "TLS CBC mode padding oracle POODLE vulnerability test"),
            ("heartbleed-probe-cli", "1.0.0-1", "OpenSSL TLS heartbeat extension memory leak probe"),
            ("shellshock-cve-tester", "1.0.0-1", "Bash environment variable function export syntax tester"),
            ("dirty-cow-probe-chk", "1.0.0-1", "Linux kernel copy-on-write race condition probe"),
            ("ebpf-program-verifier", "1.0.0-1", "eBPF bytecode instruction safety rule simulator"),
            ("kernel-kptr-restrict-chk", "1.0.0-1", "kernel kptr_restrict and dmesg_restrict setting audit"),
            ("dmesg-taint-explainer", "1.0.0-1", "Linux kernel taint bitmask flags decoder and explainer"),
        ],
    },
    "shard-21-cloud-container-runtime": {
        "section": "admin",
        "category": "Cloud Containers & Linux Namespaces",
        "description_prefix": "Container runtime and Linux namespace management utility",
        "packages": [
            ("unshare-namespace-run", "1.0.0-1", "Linux namespace unshare execution and isolation tool"),
            ("nsenter-exec-helper", "1.0.0-1", "join and execute in existing Linux namespace helper"),
            ("pivot-root-chroot-cli", "1.0.0-1", "atomic pivot_root root filesystem switching helper"),
            ("mount-namespace-view", "1.0.0-1", "mount namespace mount points and propagation viewer"),
            ("pid-namespace-tester", "1.0.0-1", "PID namespace process tree isolation and init check"),
            ("net-namespace-bridge", "1.0.0-1", "network namespace virtual ethernet pair configuration"),
            ("ipc-namespace-shm-chk", "1.0.0-1", "IPC namespace System V and POSIX shared memory view"),
            ("uts-namespace-hostname", "1.0.0-1", "UTS namespace hostname and domainname isolation tool"),
            ("user-namespace-map-uid", "1.0.0-1", "user namespace uid_map and gid_map subuid translator"),
            ("cgroup-v2-unified-tree", "1.0.0-1", "cgroup v2 unified hierarchy cgroup.procs inspector"),
            ("cgroup-v2-freeze-state", "1.0.0-1", "cgroup v2 freezer cgroup.freeze process freezer"),
            ("cgroup-v2-io-weight", "1.0.0-1", "cgroup v2 I/O weight and io.max bandwidth controller"),
            ("cgroup-v2-rdma-limit", "1.0.0-1", "cgroup v2 Remote Direct Memory Access limit view"),
            ("cgroup-v2-pids-max", "1.0.0-1", "cgroup v2 fork-bomb protection pids.max calculator"),
            ("runc-config-generator", "1.0.0-1", "OCI runc config.json container specification builder"),
            ("runc-bundle-validator", "1.0.0-1", "OCI container filesystem bundle layout validator"),
            ("crun-lightweight-exec", "1.0.0-1", "lightweight fast OCI container runtime runner"),
            ("libcontainer-spec-chk", "1.0.0-1", "libcontainer specification security constraint checker"),
            ("oci-hooks-config-tool", "1.0.0-1", "OCI runtime lifecycle hooks prestart poststop linter"),
            ("oci-runtime-metrics", "1.0.0-1", "container runtime resource utilization metric gatherer"),
            ("containerd-shim-ping", "1.0.0-1", "containerd shim v2 TTRPC communication probe"),
            ("cri-status-inspector", "1.0.0-1", "Container Runtime Interface gRPC status checker"),
            ("overlayfs-workdir-chk", "1.0.0-1", "OverlayFS workdir lowerdir upperdir validator"),
            ("overlayfs-lower-upper", "1.0.0-1", "OverlayFS multi-lower layer inheritance visualizer"),
            ("fuse-overlayfs-helper", "1.0.0-1", "unprivileged userspace FUSE OverlayFS helper tool"),
            ("devicemapper-thin-pool", "1.0.0-1", "Device Mapper thin provisioning pool metadata checker"),
            ("veth-pair-creator-cli", "1.0.0-1", "virtual ethernet veth pair link parameters calculator"),
            ("macvlan-mode-switcher", "1.0.0-1", "MACVLAN interface bridge vepa private mode viewer"),
            ("ipvlan-l2-l3-checker", "1.0.0-1", "IPVLAN L2 vs L3 mode routing and address checker"),
            ("iptables-rule-builder", "1.0.0-1", "Linux iptables container port forwarding rule builder"),
            ("nftables-rule-codegen", "1.0.0-1", "nftables table chain rule syntax generator"),
            ("ebtables-bridge-rule", "1.0.0-1", "Ethernet bridge frame table filtering rule helper"),
            ("tc-qdisc-netem-delay", "1.0.0-1", "Linux traffic control network emulation latency tool"),
            ("tc-filter-bpf-loader", "1.0.0-1", "traffic control cls_bpf packet classification helper"),
            ("container-env-sanitizer", "1.0.0-1", "container environment variable secret leak checker"),
            ("rootless-id-allocator", "1.0.0-1", "rootless container subuid and subgid range allocator"),
            ("subuid-subgid-parser", "1.0.0-1", "/etc/subuid and /etc/subgid range collision detector"),
            ("chroot-jail-builder", "1.0.0-1", "minimalist chroot directory hierarchy staging tool"),
            ("proot-ocean-binding", "1.0.0-1", "PRoot userspace chroot path binding arguments builder"),
            ("fakechroot-config-chk", "1.0.0-1", "fakechroot library interception path translator"),
            ("cap-sys-admin-check", "1.0.0-1", "CAP_SYS_ADMIN privilege escalation risk analyzer"),
            ("cap-net-raw-verifier", "1.0.0-1", "CAP_NET_RAW packet capture socket permission check"),
            ("cap-dac-override-chk", "1.0.0-1", "CAP_DAC_OVERRIDE filesystem bypass permission check"),
            ("seccomp-bpf-generator", "1.0.0-1", "seccomp Berkeley Packet Filter assembly generator"),
            ("seccomp-syscall-dump", "1.0.0-1", "Linux system call number table for AArch64 seccomp"),
            ("apparmor-profile-lint", "1.0.0-1", "AppArmor security profile rule syntax validator"),
            ("selinux-mls-level-chk", "1.0.0-1", "SELinux Multi-Level Security s0-s15 sensitivity check"),
            ("container-port-forward", "1.0.0-1", "container TCP port mapping collision detector"),
            ("container-ipam-alloc", "1.0.0-1", "container IP Address Management subnet allocator"),
            ("docker-tar-layer-extract", "1.0.0-1", "Docker image save tarball manifest and layer reader"),
        ],
    },
}
